<?php
/** @var PagSeguro_Payment_Block_Info_Ticket $this */
$info = $this->getInfo();
?>

<strong><?= $this->escapeHtml($this->getMethod()->getTitle()) ?></strong>

<?php if ($info): ?>
    <?php $additionalInformation = $info->getAdditionalInformation();?>
    <ul>
        <?php if (isset($additionalInformation['transaction_id'])): ?>
            <li>
                <strong><?= $this->__("Transaction Id: %s", $this->escapeHtml($additionalInformation['transaction_id'])) ?></strong>
            </li>
        <?php endif; ?>

        <?php if (isset($additionalInformation['pdf_ticket_url'])): ?>
            <li>
                <a href="<?= $this->escapeHtml($additionalInformation['pdf_ticket_url']); ?>" target="_blank">
                    <?= $this->__('PDF Ticket Url');?>
                </a>
            </li>
        <?php endif; ?>

        <?php if (isset($additionalInformation['png_ticket_url'])): ?>
            <li>
                <a href="<?= $this->escapeHtml($additionalInformation['png_ticket_url']); ?>" target="_blank">
                    <?= $this->__('PNG Ticket Url');?>
                </a>
            </li>
        <?php endif; ?>
    </ul>
<?php endif; ?>