<?php
/** @var PagSeguro_Payment_Block_Form_Twocc $this */
$code = $this->getMethodCode();
$isCurrentlySecure = Mage::app()->getStore()->isCurrentlySecure();
$quote = $this->_getHelper()->getSession()->getQuote();
$baseGrandTotal = $quote->getBaseGrandTotal();
$canSave = $this->_getHelper()->getConfig('cc_can_save', $code);
$savedCards = $this->getSavedCards();
$useEncryption = $this->_getHelper()->getConfig('use_pagseguro_encrypted_card', $code);
$isAvailable = $this->_getHelper()->getMethodIsAvailable($code, $baseGrandTotal, 2);
?>
<?php if (!$isAvailable['is_available']) : ?>
<fieldset class="form-list" id="fieldset_<?= $code ?>_unavailable">
    <p><?= $this->__('Payment method not available! Grand total is not valid to installments amount') ?></p>
    <p><?= $this->__("<strong>Grand Total:</strong> %s", $this->_getHelper()->formatCurrency($baseGrandTotal)) ?></p>

    <?php if (isset($isAvailable['min_value'])) : ?>
        <p><?= $this->__("<strong>Min value:</strong> %s", $this->_getHelper()->formatCurrency($isAvailable['min_value']))?></p>
    <?php endif ;?>
</fieldset>
<?php else : ?>
<fieldset class="form-list">
    <div id="payment_form_<?= $code ?>" class="case pagseguro-payment-one-cc pagseguro-payment-cc"
         style="display:none;">
        <div class="entry-title">
            <h4><?= $this->__("Order Total Amount: %s", $this->_getHelper()->formatCurrency($baseGrandTotal)) ?></h4>
        </div>

        <?php foreach ($this->getCardsNames() as $cardName) : ?>
            <div class="card-entry pagseguro-card-entry">
                <div class="entry-title">
                    <h4><?= $cardName == 'card_one' ? $this->__('First Card') : $this->__('Second Card'); ?></h4>
                </div>

                <?php if (!$useEncryption && $canSave && $savedCards && $savedCards->getSize()) : ?>
                    <input type="hidden" name="payment[<?= $cardName ?>][use_saved_card]" id="pagseguro<?= $cardName ?>_use_save_card"
                           value="0"/>

                    <div class="save-card-button">
                        <a class="button btn" href="javascript:void(0)" id="<?= $cardName ?>_use_save_card">
                            <?= $this->__('Use saved card') ?>
                        </a>

                        <a class="button btn" href="javascript:void(0)" id="<?= $cardName ?>_use_new_card" style="display:none">
                            <?= $this->__('Use new card') ?>
                        </a>
                    </div>

                    <div id="<?= $cardName ?>_saved_cards" class="input-box" style="display:none;">
                        <div class="exp input-box">
                            <h4><?= $this->__('Saved Cards') ?></h4>
                            <div class="saved-card input-box">
                                <label for="savedCard">
                                    <?= $this->__('Card Number') ?>
                                </label>
                                <select name="payment[<?= $cardName ?>][cc_token]" id="savedCard">
                                    <option value="0"><?= $this->__('Choose...'); ?></option>
                                    <?php /** @var PagSeguro_Payment_Model_Card $card */ ?>
                                    <?php foreach ($savedCards as $card) : ?>
                                        <option value="<?= $card->getId() ?>">
                                            <?= $card->getDescription(); ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>

                <div class="cc_form <?= $cardName ?>_cc_form">
                    <div class="input-box radio-flags">
                        <?php foreach ($this->_getHelper()->getMethods($code) as $method) : ?>
                            <?php $slug = $method['slug']; ?>
                            <label>
                                <input type="radio" name="payment[<?= $cardName ?>][cc_type]"
                                       class="pagseguro-cc-type pagseguro-<?= $cardName ?>-cc-type"
                                       title="<?= $method['label']; ?>" value="<?= $method['value'] ?>"/>

                                <img src="<?= $this->_getHelper()->getCardImagePath() . $method['slug']; ?>.svg"
                                     alt="<?= $this->__($method['label']) ?>" title="<?= $this->__($method['label']) ?>"
                                />
                            </label>
                        <?php endforeach; ?>
                    </div>

                    <div class="cc_grid" id="pagseguro_two_cc">
                        <?php if ($quote->getCheckoutMethod() != 'guest' && $canSave && !$useEncryption): ?>
                            <label for="<?= $cardName ?>_ck_save_card">
                                <?= $this->__('Save this card?') ?>
                            </label>
                            <input type="checkbox" name="payment[<?= $cardName ?>][save_card]" id="<?= $cardName ?>_ck_save_card"/>
                        <?php endif; ?>

                        <div class="num input-box div-cc-number">
                            <label class="required">
                                <em>*</em><?= $this->__('Card Number') ?>
                            </label>
                            <input type="number" placeholder="<?= $this->__('Type Only Numbers') ?>"
                                   id="<?= "{$code}_{$cardName}" ?>_number" name="payment[<?= $cardName ?>][cc_number]"
                                   title="<?= $this->__('Card Number') ?>"
                                   class="input-text validate-cc-number-pagseguropayment required-entry"
                            />
                        </div>

                        <div class="div_cc_name nome input-box">
                            <label for="<?= $code ?>_owner" class="required">
                                <em>*</em><?= $this->__('Owner Name') ?>
                            </label>

                            <input type="text" placeholder="<?= $this->__('Exactly as the card') ?>"
                                   title="<?= $this->__('Owner Name') ?>" class="required-entry input-text"
                                   id="<?= "{$code}_{$cardName}" ?>_owner" name="payment[<?= $cardName ?>][cc_owner]"
                                   />
                        </div>

                        <div class="exp input-box div_cc_expiration">
                            <label for="<?= $code ?>_expiration_month" class="required">
                                <em>*</em><?= $this->__('Validate') ?>
                            </label>

                            <span class="month">
                                <select id="<?= "{$code}_{$cardName}" ?>_expiration_month"
                                        name="payment[<?= $cardName ?>][cc_exp_month]"
                                        class="exp-month required-entry expiration">
                                    <?php $ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                                    <?php foreach ($this->getCcMonths() as $key => $label): ?>
                                        <?php $value = is_numeric($key) ? $key + 1 : null; ?>
                                        <option value="<?= $value ?>">
                                            <?= $label ?>
                                        </option>
                                    <?php endforeach ?>
                                </select>
                            </span>

                            <span class="year">
                                <?php $ccExpYear = $this->getInfoData('cc_exp_year') ?>
                                <select id="<?= "{$code}_{$cardName}" ?>_expiration_year" style="width:103px;"
                                        name="payment[<?= $cardName ?>][cc_exp_year]"
                                        class="exp-year required-entry expiration">
                                    <?php foreach ($this->getCcYears() as $key => $year): ?>
                                        <?php $value = ((int)$year) > 0 ? (int)$year : null; ?>
                                        <option value="<?= $value ?>">
                                            <?= $year ?>
                                        </option>
                                    <?php endforeach ?>
                                </select>
                            </span>
                        </div>
                    </div>
                </div>

                <?php if ($useEncryption) : ?>
                    <input name="payment[<?= $cardName ?>][encrypted]" id="encrypted_card_<?= $cardName ?>"
                           type="hidden">
                <?php endif; ?>

                <div class="input-box div_cvv">
                    <label for="<?= $code ?>_cvv" class="required">
                        <em>*</em><?= $this->__('CVV') ?>
                    </label>
                    <input type="text" title="<?= $this->__('CVV') ?>" class="required-entry input-text cvv"
                           id="<?= "{$code}_{$cardName}" ?>_cid" <?= !$useEncryption ? 'name="payment[' . $cardName . '][cc_cid]"' : null ?> />
                </div>

                <div class="num input-box">
                    <label class="required">
                        <em>*</em><?= $this->__('Value on this card') ?>
                    </label>
                    <input type="number" step="any" min="0"
                           id="<?= "{$code}_{$cardName}" ?>_amount" name="payment[<?= $cardName ?>][amount]"
                           title="<?= $this->__('Card Amount') ?>" class="input-text required-entry price-box"
                    />
                </div>

                <?php if (!$this->_getHelper()->getConfig('installments', $code)): ?>
                    <input type="hidden" name="payment[<?= $cardName ?>][installments]" value="1"/>
                <?php else: ?>
                    <div class="pars input-box">
                        <label for="pagseguro_one_cc_installments" class="required">
                            <em>*</em><?= $this->__('Installments Number') ?>
                        </label>

                        <select name="payment[<?= $cardName ?>][installments]" id="pagseguropayment_twocc_<?= $cardName ?>_installments"
                                class="required-entry">
                            <option value=""><?= $this->__('Choose'); ?></option>
                        </select>
                    </div>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>

        <input type="hidden" name="payment[base_grand_total]" value="<?= $baseGrandTotal; ?>"/>
    </div>
</fieldset>

<script type="text/javascript">
    pagseguropayment.grand_total = parseFloat("<?= $baseGrandTotal; ?>");
    pagseguropayment.interestType = "<?= $this->_getHelper()->getConfig('interest_type', $code); ?>";
    pagseguropayment.installments = "<?= $this->_getHelper()->getConfig('max_installments', $code); ?>";
    pagseguropayment.minInstallmentValue = parseFloat("<?= $this->_getHelper()->getConfig('minimum_installments_value', $code); ?>");
    pagseguropayment.noInterestInstallments = parseFloat("<?= $this->_getHelper()->getConfig('installments_without_interest_rate', $code); ?>");
    pagseguropayment.interestRate = parseFloat("<?= $this->_getHelper()->getConfig('interest_rate', $code); ?>");

    <?php if ($useEncryption) : ?>
    $j(document).ready(function () {
        $j('#payment-buttons-container button').on('click', function () {
            let publicKey = '<?= $this->_getHelper()->getPublicKey() ?>';
            <?php foreach ($this->getCardsNames() as $cardsName) : ?>
                var encriptedData = pagseguropayment.encryptCard('<?= "{$code}_{$cardsName}"?>', publicKey);
                $j('#encrypted_card_' + '<?= $cardsName ?>').val(encriptedData);
            <?php endforeach; ?>
        });
    });
    <?php endif; ?>


    <?php foreach ($this->getCardsNames() as $cardName) : ?>
        $j('#<?= $cardName ?>_use_save_card').click(function () {
            $j(this).css('display', 'none');
            $j('.<?= $cardName ?>_cc_form').css('display', 'none');
            $j('#<?= $cardName ?>_saved_cards').css('display', 'block');
            $j('#<?= $cardName ?>_use_new_card').css('display', '-webkit-inline-box');
            $j('#pagseguro<?= $cardName ?>_use_save_card').val(1);
        });

        $j('#<?= $cardName ?>_use_new_card').click(function () {
            $j(this).css('display', 'none');
            $j('.<?= $cardName ?>_cc_form').css('display', 'block');
            $j('#<?= $cardName ?>_saved_cards').css('display', 'none');
            $j('#<?= $cardName ?>_use_save_card').css('display', '-webkit-inline-box');
            $j('#pagseguro<?= $cardName ?>_use_save_card').val(0);
        });

        $j('#payment_form_<?= "$code" ?> input.pagseguro-<?= $cardName ?>-cc-type').click(function () {
            $j('#payment_form_<?= "$code" ?> input.pagseguro-<?= $cardName ?>-cc-type').parent().find('img').removeClass('on');
            $j('#payment_form_<?= "$code" ?> input.pagseguro-<?= $cardName ?>-cc-type').parent().find('img').addClass('off');

            $j(this).parent().find('img').removeClass('off');
            $j(this).parent().find('img').addClass('on');
        });

        $j('#payment_form_<?= $code ?> #<?= "{$code}_{$cardName}" ?>_number').on('click, keyup', function () {
            var ccType = pagseguropayment.identifyCcNumber($j(this).val());
            $j('#payment_form_<?= $code ?> input.pagseguro-<?= $cardName ?>-cc-type').each(function () {
                if ($j(this).val() == ccType) {
                    $j(this).click();
                }
            });
        });

        $j('#payment_form_<?= $code ?> #<?= "{$code}_{$cardName}" ?>_amount').on('click, keyup', function () {
            pagseguropayment.updateTwoCardAmount($j(this).val(), '<?= $cardName ?>');
        });
    <?php endforeach; ?>
</script>
<?php endif; ?>